name: backend
description: A server app using the shelf package and Docker.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  shelf_cors_headers: ^0.1.5
  dotenv: ^4.2.0
  collection: ^1.18.0
  dart_jsonwebtoken: ^2.10.0
  http_server: ^1.0.0
  http: ^1.1.0
  firedart: ^0.9.8   # Client Firestore per Dart puro (non-Flutter)
  crypto: ^3.0.7
  mockito: ^5.6.1
  build_runner: ^2.10.4
  googleapis_auth: ^1.6.0

  # dipendenza comune
  data_models:
    path: ../data_models

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0